// Product

export const storeProduct = [
  {
    id: 1,
    title: "Google Pixel - Black",
    img: "./images/product-1.png",
    price: 10,
    company: "GOOGLE",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 5,
    sale: 5,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 2,
    title: "Samsung S7",
    img: "./images/product-2.png",
    price: 16,
    company: "SAMSUNG",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 10,
    sale: 10,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 3,
    title: "HTC 10 - Black",
    img: "./images/product-3.png",
    price: 8,
    company: "htc",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 8,
    sale: 7,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 4,
    title: "HTC 10 - White",
    img: "./images/product-4.png",
    price: 18,
    company: "htc",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 9,
    sale: 0,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 5,
    title: "HTC Desire 626s",
    img: "./images/product-5.png",
    price: 24,
    company: "htc",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 4,
    sale: 0,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 6,
    title: "Vintage Iphone",
    img: "./images/product-6.png",
    price: 17,
    company: "apple",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 2,
    sale: 15,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 7,
    title: "Iphone 7",
    img: "./images/product-7.png",
    price: 30,
    company: "apple",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 1,
    sale: 0,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 8,
    title: "Smashed Iphone",
    img: "./images/product-8.png",
    price: 2,
    company: "apple",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 1,
    sale: 0,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 9,
    title: "Xiaomi Mi Band 3",
    img: "./images/product-9.png",
    price: 11,
    company: "Xiaomi Mi",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 1,
    sale: 0,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: true,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 10,
    title: "Lenovo IdeaPad L340",
    img: "./images/product-10.png",
    price: 80,
    company: "Lenovo",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 2,
    buy_count: 1,
    sale: 10,
    slide: false,
    specialWidth: true,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 11,
    title: "Кресло INDI CA-1613A-1",
    img: "./images/product-11.png",
    price: 8,
    company: "INDI",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 3,
    buy_count: 1,
    sale: 5,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 12,
    title: "Holitic Change",
    img: "./images/product-12.png",
    price: 8,
    company: "Asaxiy UZ",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 4,
    buy_count: 20,
    sale: 5,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 13,
    title: "HyperX Cloud Stinger",
    img: "./images/product-13.png",
    price: 2,
    company: "HyperX ",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 30,
    sale: 5,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: true,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
  {
    id: 14,
    title: "HyperX Cloud Stinger",
    img: "./images/product-14.png",
    price: 25,
    company: "HyperX ",
    info:
      "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
    category: 1,
    buy_count: 20,
    sale: 5,
    slide: false,
    specialWidth: false,
    specialHeight: false,
    specialMiddleL1: false,
    specialMiddleL2: false,
    specialMiddleR1: false,
    specialMiddleR2: false,
  },
];

export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: "./images/product-1.png",
  price: 10,
  company: "google",
  info:
    "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
  category: 1,
  buy_count: 4,
  sale: 5,
  slide: false,
  specialWidth: false,
  specialHeight: false,
  specialMiddleL1: false,
  specialMiddleL2: false,
  specialMiddleR1: false,
  specialMiddleR2: false,
};
